ALTER VIEW Apra.ConstituentsView AS

SELECT DISTINCT
C.[CONSTITUENT_ID],
[MANAGED_PROSPECT],
[LIFETIME_GIVING],
CASE WHEN [LIFETIME_GIVING] >= 1 THEN 1 ELSE 0 END AS "Donor",
CASE WHEN [LIFETIME_GIVING] >= 100000 THEN 1 ELSE 0 END AS "Major Donor",
[LIFETIME_GIFT_COUNT],
[FIRST_GIFT_DATE],
[LAST_GIFT_DATE], 
CASE WHEN [FIRST_GIFT_DATE] = 'NA' THEN 0 ELSE DATEDIFF(YEAR, CONVERT(DATE,[FIRST_GIFT_DATE]), CONVERT(DATE,[LAST_GIFT_DATE])) END + 1 AS "Years of Giving",

----- CRM INTERACTION COUNTS - LIFETIME
[LIFETIME_CRM_INTERACTIONS],
(SELECT COUNT(DISTINCT I.CRM_INTERACTION_DATE) FROM Apra.[CRM Interactions] I WITH (NOLOCK) WHERE I.CONSTITUENT_ID = C.CONSTITUENT_ID AND I.CRM_INTERACTION_TYPE IN ('Visit','Virtual Visit')) AS "Lifetime Visits",
(SELECT COUNT(DISTINCT I.CRM_INTERACTION_DATE) FROM Apra.[CRM Interactions] I WITH (NOLOCK) WHERE I.CONSTITUENT_ID = C.CONSTITUENT_ID AND I.CRM_INTERACTION_TYPE = 'Phone') AS "Lifetime Phone Calls",
(SELECT COUNT(DISTINCT I.CRM_INTERACTION_DATE) FROM Apra.[CRM Interactions] I WITH (NOLOCK) WHERE I.CONSTITUENT_ID = C.CONSTITUENT_ID AND I.CRM_INTERACTION_TYPE = 'Correspondence') AS "Lifetime Correspondences",

----- CRM INTERACTION COUNTS - LAST 5 YEARS
(SELECT COUNT(DISTINCT I.CRM_INTERACTION_DATE) FROM Apra.[CRM Interactions] I WITH (NOLOCK) WHERE I.CONSTITUENT_ID = C.CONSTITUENT_ID AND I.CRM_INTERACTION_DATE >= GETDATE() - (365.25*5)) AS "Interactions L5Y",
(SELECT COUNT(DISTINCT I.CRM_INTERACTION_DATE) FROM Apra.[CRM Interactions] I WITH (NOLOCK) WHERE I.CONSTITUENT_ID = C.CONSTITUENT_ID AND I.CRM_INTERACTION_TYPE IN ('Visit','Virtual Visit') AND I.CRM_INTERACTION_DATE >= GETDATE() - (365.25*5)) AS "Visits L5Y",
(SELECT COUNT(DISTINCT I.CRM_INTERACTION_DATE) FROM Apra.[CRM Interactions] I WITH (NOLOCK) WHERE I.CONSTITUENT_ID = C.CONSTITUENT_ID AND I.CRM_INTERACTION_TYPE = 'Phone' AND I.CRM_INTERACTION_DATE >= GETDATE() - (365.25*5)) AS "Phone Calls L5Y",
(SELECT COUNT(DISTINCT I.CRM_INTERACTION_DATE) FROM Apra.[CRM Interactions] I WITH (NOLOCK) WHERE I.CONSTITUENT_ID = C.CONSTITUENT_ID AND I.CRM_INTERACTION_TYPE = 'Correspondence' AND I.CRM_INTERACTION_DATE >= GETDATE() - (365.25*5)) AS "Correspondences L5Y",

----- CRM INTERACTION COUNTS - PRIOR TO FIRST GIFT
(SELECT COUNT(DISTINCT I.CRM_INTERACTION_DATE) FROM Apra.[CRM Interactions] I WITH (NOLOCK) WHERE I.CONSTITUENT_ID = C.CONSTITUENT_ID AND I.CRM_INTERACTION_DATE <= CONVERT(DATE,REPLACE(C.FIRST_GIFT_DATE,'NA','1901-01-01'))) AS "Interactions Prior to First Gift",
(SELECT COUNT(DISTINCT I.CRM_INTERACTION_DATE) FROM Apra.[CRM Interactions] I WITH (NOLOCK) WHERE I.CONSTITUENT_ID = C.CONSTITUENT_ID AND I.CRM_INTERACTION_TYPE IN ('Visit','Virtual Visit') AND I.CRM_INTERACTION_DATE <= CONVERT(DATE,REPLACE(C.FIRST_GIFT_DATE,'NA','1901-01-01'))) AS "Visits Prior to First Gift",
(SELECT COUNT(DISTINCT I.CRM_INTERACTION_DATE) FROM Apra.[CRM Interactions] I WITH (NOLOCK) WHERE I.CONSTITUENT_ID = C.CONSTITUENT_ID AND I.CRM_INTERACTION_TYPE = 'Phone' AND I.CRM_INTERACTION_DATE <= CONVERT(DATE,REPLACE(C.FIRST_GIFT_DATE,'NA','1901-01-01'))) AS "Phone Calls Prior to First Gift",
(SELECT COUNT(DISTINCT I.CRM_INTERACTION_DATE) FROM Apra.[CRM Interactions] I WITH (NOLOCK) WHERE I.CONSTITUENT_ID = C.CONSTITUENT_ID AND I.CRM_INTERACTION_TYPE = 'Correspondence' AND I.CRM_INTERACTION_DATE <= CONVERT(DATE,REPLACE(C.FIRST_GIFT_DATE,'NA','1901-01-01'))) AS "Correspondences Prior to First Gift",

----- VIDEO EMAILS OPENED LIFETIME
(SELECT COUNT(DISTINCT V.CONTACT_ID) FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.OPENED_DATE NOT IN ('NA')) AS "Lifetime Video Emails Opened",
(SELECT SUM(CAST(V.CLICKS AS INT)) FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID) AS "Lifetime Video Emails Clicked",
(SELECT SUM(CAST(V.VIDEO_VIEWS AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID) AS "Lifetime Video Views",
(SELECT SUM(CAST(V.STARTED_VIDEO AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID) AS "Lifetime Videos Started",
(SELECT SUM(CAST(V.WATCHED_VIDEO_25_PERCENT AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID) AS "Lifetime Videos Watched 25 Percent",
(SELECT SUM(CAST(V.WATCHED_VIDEO_50_PERCENT AS INT)) FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID) AS "Lifetime Videos Watched 50 Percent",
(SELECT SUM(CAST(V.WATCHED_VIDEO_75_PERCENT AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID) AS "Lifetime Videos Watched 75 Percent",
(SELECT SUM(CAST(V.FINISHED_VIDEO AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID) AS "Lifetime Videos Finished",
(SELECT SUM(CAST(V.VIDEO_SHARES_TO_FACEBOOK AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID) AS "Lifetime Video Shares to Facebook",

----- VIDEO EMAILS OPENED LAST 5 YEARS
(SELECT COUNT(DISTINCT V.CONTACT_ID) FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.OPENED_DATE NOT IN ('NA') AND V.SENT_DATE >= GETDATE() - (365.25*5)) AS "L5Y Video Emails Opened",
(SELECT SUM(CAST(V.CLICKS AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.SENT_DATE >= GETDATE() - (365.25*5)) AS "L5Y Video Emails Clicked",
(SELECT SUM(CAST(V.VIDEO_VIEWS AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.SENT_DATE >= GETDATE() - (365.25*5)) AS "L5Y Video Views",
(SELECT SUM(CAST(V.STARTED_VIDEO AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.SENT_DATE >= GETDATE() - (365.25*5)) AS "L5Y Videos Started",
(SELECT SUM(CAST(V.WATCHED_VIDEO_25_PERCENT AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.SENT_DATE >= GETDATE() - (365.25*5)) AS "L5Y Videos Watched 25 Percent",
(SELECT SUM(CAST(V.WATCHED_VIDEO_50_PERCENT AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.SENT_DATE >= GETDATE() - (365.25*5)) AS "L5Y Videos Watched 50 Percent",
(SELECT SUM(CAST(V.WATCHED_VIDEO_75_PERCENT AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.SENT_DATE >= GETDATE() - (365.25*5)) AS "L5Y Videos Watched 75 Percent",
(SELECT SUM(CAST(V.FINISHED_VIDEO AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.SENT_DATE >= GETDATE() - (365.25*5)) AS "L5Y Videos Finished",
(SELECT SUM(CAST(V.VIDEO_SHARES_TO_FACEBOOK AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.SENT_DATE >= GETDATE() - (365.25*5)) AS "L5Y Video Shares to Facebook",

----- VIDEO EMAILS OPENED PRIOR TO FIRST GIFT
(SELECT COUNT(DISTINCT V.CONTACT_ID) FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.OPENED_DATE NOT IN ('NA') AND V.SENT_DATE <= CONVERT(DATE,REPLACE(C.FIRST_GIFT_DATE,'NA','1901-01-01'))) AS "Before First Gift Video Emails Opened",
(SELECT SUM(CAST(V.CLICKS AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.SENT_DATE <= CONVERT(DATE,REPLACE(C.FIRST_GIFT_DATE,'NA','1901-01-01'))) AS "Before First Gift Video Emails Clicked",
(SELECT SUM(CAST(V.VIDEO_VIEWS AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.SENT_DATE <= CONVERT(DATE,REPLACE(C.FIRST_GIFT_DATE,'NA','1901-01-01'))) AS "Before First Gift Video Views",
(SELECT SUM(CAST(V.STARTED_VIDEO AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.SENT_DATE <= CONVERT(DATE,REPLACE(C.FIRST_GIFT_DATE,'NA','1901-01-01'))) AS "Before First Gift Videos Started",
(SELECT SUM(CAST(V.WATCHED_VIDEO_25_PERCENT AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.SENT_DATE <= CONVERT(DATE,REPLACE(C.FIRST_GIFT_DATE,'NA','1901-01-01'))) AS "Before First Gift Videos Watched 25 Percent",
(SELECT SUM(CAST(V.WATCHED_VIDEO_50_PERCENT AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.SENT_DATE <= CONVERT(DATE,REPLACE(C.FIRST_GIFT_DATE,'NA','1901-01-01'))) AS "Before First Gift Videos Watched 50 Percent",
(SELECT SUM(CAST(V.WATCHED_VIDEO_75_PERCENT AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.SENT_DATE <= CONVERT(DATE,REPLACE(C.FIRST_GIFT_DATE,'NA','1901-01-01'))) AS "Before First Gift Videos Watched 75 Percent",
(SELECT SUM(CAST(V.FINISHED_VIDEO AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.SENT_DATE <= CONVERT(DATE,REPLACE(C.FIRST_GIFT_DATE,'NA','1901-01-01'))) AS "Before First Gift Videos Finished",
(SELECT SUM(CAST(V.VIDEO_SHARES_TO_FACEBOOK AS INT))  FROM Apra.[Video Email Data] V WITH (NOLOCK) WHERE V.CONSTITUENT_ID = C.CONSTITUENT_ID AND V.SENT_DATE <= CONVERT(DATE,REPLACE(C.FIRST_GIFT_DATE,'NA','1901-01-01'))) AS "Before First Gift Video Shares to Facebook",

[FIRST_CRM_INTERACTION_DATE],
[LAST_CRM_INTERACTION_DATE],
[CAPACITY_ESTIMATE],
[CAPACITY_ESTIMATE_CLEAN],
[LIFETIME_GIVING_BAND],
[LIFETIME_GIVING_BAND_LOW],
[FIVE_YEAR_GIVING_BAND],
[FIVE_YEAR_GIVING_BAND_LOW],
[R_Score],
[F_Score],
[M_Score],
[RFM_Score_Sum],
[RFM_Segment]

FROM [Philanthropy].[Apra].[Constituents] C WITH (NOLOCK)
LEFT OUTER JOIN Apra.Gifts G WITH (NOLOCK) ON C.CONSTITUENT_ID = G.CONSTITUENT_ID
LEFT OUTER JOIN Apra.[Video Email Data] V WITH (NOLOCK) ON C.CONSTITUENT_ID = V.CONSTITUENT_ID


GROUP BY
C.[CONSTITUENT_ID],
[MANAGED_PROSPECT],
[LIFETIME_GIVING],
[LIFETIME_GIFT_COUNT],
[FIRST_GIFT_DATE],
[LAST_GIFT_DATE],
[LIFETIME_CRM_INTERACTIONS],
[FIRST_CRM_INTERACTION_DATE],
[LAST_CRM_INTERACTION_DATE],
[CAPACITY_ESTIMATE],
[CAPACITY_ESTIMATE_CLEAN],
[LIFETIME_GIVING_BAND],
[LIFETIME_GIVING_BAND_LOW],
[FIVE_YEAR_GIVING_BAND],
[FIVE_YEAR_GIVING_BAND_LOW],
[R_Score],
[F_Score],
[M_Score],
[RFM_Score_Sum],
[RFM_Segment]

GO