USE [APRA-IL]
GO

/****** Object:  StoredProcedure [dbo].[Delete_Future_Events]    Script Date: 3/1/2025 9:46:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[Delete_Future_Events] AS

----- DELETE FROM EVENT REGISTRATION FIELDS TABLE -----
DELETE EF
FROM DBO.EventRegistrationFields EF WITH (NOLOCK)
INNER JOIN DBO.[Events] E WITH (NOLOCK) ON EF.[Event ID] = E.[Event ID]
WHERE
CONVERT(DATE,LEFT(E.[Start Date],10)) >= GETDATE() - 14

----- DELETE FROM EVENT REGISTRATIONS TABLE -----
DELETE ER
FROM DBO.EventRegistrations ER WITH (NOLOCK)
INNER JOIN DBO.[Events] E WITH (NOLOCK) ON ER.[Event ID] = E.[Event ID]
WHERE
CONVERT(DATE,LEFT(E.[Start Date],10)) >= GETDATE() - 14

----- DELETE FROM EVENT REGISTRATION TYPES TABLE -----
DELETE ERT
FROM DBO.EventRegistrationTypes ERT WITH (NOLOCK)
INNER JOIN DBO.[Events] E WITH (NOLOCK) ON ERT.[Event ID] = E.[Event ID]
WHERE
CONVERT(DATE,LEFT(E.[Start Date],10)) >= GETDATE() - 14

----- DELETE FROM EVENT TAGS TABLE -----
DELETE ET
FROM DBO.EventTags ET WITH (NOLOCK)
INNER JOIN DBO.[Events] E WITH (NOLOCK) ON ET.[Event ID] = E.[Event ID]
WHERE
CONVERT(DATE,LEFT(E.[Start Date],10)) >= GETDATE() - 14

----- DELETE FROM EVENTS TABLE -----
DELETE E
FROM DBO.[Events] E WITH (NOLOCK)
WHERE
CONVERT(DATE,LEFT(E.[Start Date],10)) >= GETDATE() - 14

GO


