USE [APRA-IL]
GO

/****** Object:  View [dbo].[Organization_Crosswalk]    Script Date: 2/27/2025 9:39:01 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[Organization_Crosswalk] AS

SELECT DISTINCT 
C.Organization,

REPLACE(
ISNULL(CASE
WHEN C.[Organization] LIKE 'Advocate%' THEN 'Advocate Health Care'
WHEN C.Organization LIKE '%Lurie Children%' THEN 'Ann & Robert H. Lurie Children''s Hospital of Chicago'
WHEN C.Organization LIKE 'Aspire%' THEN 'Aspire Research Group'
WHEN C.Organization LIKE '%Whaley%%Flessner%' THEN 'BWF'
WHEN C.Organization LIKE '%WTTW%' THEN 'WTTW/Chicago PBS and WFMT Chicago'
WHEN C.Organization = 'WWF' THEN 'World Wildlife Fund'
WHEN C.Organization LIKE '%Central Michigan%' THEN 'Central Michigan University'
WHEN C.Organization LIKE '%Wisconsin Foundation%' THEN 'University of Wisconsin Foundation'
WHEN C.Organization = 'UW Foundation' THEN 'University of Wisconsin Foundation'
WHEN C.Organization = 'WAKE FOREST' THEN 'Wake Forest University'
WHEN C.Organization LIKE '%Villanova%' THEN 'Villanova University'
WHEN C.Organization = 'VCU' THEN 'Virginia Commonwealth University'
WHEN C.Organization = 'UVA' THEN 'University of Virginia'
WHEN C.Organization = 'UTMD Anderson Cancer Center' THEN 'MD Anderson Cancer Center'
WHEN C.Organization = 'USC' THEN 'University of Southern California'
WHEN C.Organization = 'University of WA' THEN 'University of Washington'
WHEN C.Organization LIKE '%University of Texas%%Austin%' THEN 'University of Texas at Austin'
WHEN C.Organization = 'University of North Texas Health Science Center' THEN 'University of North Texas'
WHEN C.Organization LIKE '%Michigan Medicine%' THEN 'University of Michigan Medicine'
WHEN C.Organization LIKE 'University of Michigan%' THEN 'University of Michigan'
WHEN C.Organization = 'University Advancement - UW-Milwaukee' THEN 'University of Wisconsin-Milwaukee'
WHEN C.Organization LIKE 'Indiana University%' THEN 'Indiana University Foundation'
WHEN C.Organization IN ('IU Foundation','IU Lilly Family School of Philanthropy') THEN 'Indiana University Foundation'
WHEN C.Organization = 'IN 4-H Foundation' THEN 'Indiana 4-H Foundation'
WHEN C.Organization LIKE 'Harvard%' THEN 'Harvard University'
WHEN C.Organization LIKE 'Shedd%' THEN 'Shedd Aquarium'
WHEN C.Organization = 'SMU' THEN 'Southern Methodist University'
WHEN C.Organization LIKE 'Advizor%' THEN 'Advizor Solutions, Inc.'
WHEN C.Organization LIKE 'CHI Health%' THEN 'CHI Health Foundation'
WHEN C.Organization = 'Sinai health Foundation' THEN 'Sinai Health Foundation'
WHEN C.Organization LIKE '%SELF%%EMPLOYED%%' THEN 'Self-employed'
WHEN C.Organization LIKE '%Henry Ford%%' THEN 'Henry Ford Health System'
WHEN C.Organization LIKE 'Georgetown University%' THEN 'Georgetown University'
WHEN C.Organization = 'GCFD' THEN 'Greater Chicago Food Depository'
WHEN C.Organization LIKE '%Marts%%Lundy%' THEN 'Marts&Lundy'
WHEN C.Organization LIKE 'College of the Mainland%' THEN 'College of the Mainland Foundation'
WHEN C.Organization IN ('Loyola University Chicago','Loyola University of Chicago') THEN 'Loyola University Chicago'
WHEN C.Organization IN ('Loyola University Health System','Loyola University Medical Center') THEN 'Loyola Medicine'
WHEN C.Organization LIKE 'Southern Illinois University%' THEN 'Southern Illinois University'
WHEN C.Organization LIKE 'SIU%' THEN 'Southern Illinois University'
WHEN C.Organization IN ('Northwestern Medicine','NMF','Northwestern Memorial Foundation','Northwestern Memorial HealthCare') THEN 'Northwestern Memorial Foundation'
WHEN C.Organization LIKE 'Northweste%%U%' THEN 'Northwestern University'
WHEN C.Organization LIKE '%Feinberg%%Medicine%' THEN 'Northwestern University'
WHEN C.Organization LIKE '%Kellogg%' THEN 'Northwestern University'
WHEN C.Organization LIKE '%University of Miami%' THEN 'University of Miami'
WHEN C.Organization LIKE '%University of Cincinnati%' THEN 'The University of Cincinnati Foundation'
WHEN C.Organization LIKE '%UNICEF%' THEN 'UNICEF'
WHEN C.Organization = 'KSU Foundation' THEN 'Kansas State University Foundation'
WHEN C.Organization LIKE '%The Salvation Army%' THEN 'The Salvation Army'
WHEN C.Organization = 'MCW' THEN 'Medical College of Wisconsin'
WHEN C.Organization = 'MIT' THEN 'Massachusetts Institute of Technology'
WHEN C.Organization LIKE '%University of Chicago%' THEN 'University of Chicago'
WHEN C.Organization LIKE 'U Chicago%' THEN 'University of Chicago'
WHEN C.Organization LIKE '%Northern Illinois U%' THEN 'Northern Illinois University Foundation'
WHEN C.Organization LIKE 'NIU%' THEN 'Northern Illinois University Foundation'
WHEN C.Organization LIKE '%Booth%' THEN 'University of Chicago'
WHEN C.Organization = 'american dental association' THEN 'American Dental Association'
WHEN C.Organization = 'Cal State LA' THEN 'California State University, Los Angeles'
WHEN C.Organization LIKE 'CCS%' THEN 'CCS Fundraising'
WHEN C.Organization = 'Columbia Business School' THEN 'Columbia University'
WHEN C.Organization = 'Connecticut college' THEN 'Connecticut College'
WHEN C.Organization = 'CSU San Bernardino' THEN 'California State University, San Bernardino'
WHEN C.Organization = 'CWF' THEN 'The Colonial Williamsburg Foundation'
WHEN C.Organization = 'Diocese of PUeblo' THEN 'Diocese of Pueblo'
WHEN C.Organization = 'DPL' THEN 'Chicago Public Library'
WHEN C.Organization LIKE 'Emory%' THEN 'Emory University'
WHEN C.Organization = 'Illinois Easter' THEN 'Eastern Illinois University'
WHEN C.Organization IN ('Independent','Independent Prospect Researcher','N/A','Unaffiliated','NA','None','The') THEN ''
WHEN C.Organization = 'INDIANA WESLEYAN UNIVERSITY' THEN 'Indiana Wesleyan University'
WHEN C.Organization LIKE '%Christians and Jews%' THEN 'International Fellowship of Christians and Jews'
WHEN C.Organization LIKE '%JDRF%' THEN 'Breakthrough T1D'
WHEN C.Organization = 'WCU Foundation' THEN 'West Chester University Foundation'
WHEN C.Organization LIKE '%Vassar%' THEN 'Vassar College'
WHEN C.Organization LIKE '%University%%Thomas%' THEN 'University of St. Thomas'
WHEN C.Organization LIKE '%University of Central Florida%' THEN 'University of Central Florida'
WHEN C.Organization LIKE '%UCF %' THEN 'University of Central Florida'
WHEN C.Organization = 'University of Central' THEN 'University of Central Florida'
WHEN C.Organization LIKE '%Trust for Public Land%' THEN 'The Trust for Public Land'
WHEN C.Organization LIKE '%Field Museum%' THEN 'The Field Museum'
WHEN C.Organization LIKE '%Art Institute of Chicago%' THEN 'Art Institute of Chicago'
WHEN C.Organization LIKE '%Neal%%Eisenberg%' THEN 'Neal Gerber Eisenberg LLP'
WHEN C.Organization LIKE '%Museum of Science&&Industry%' THEN 'Museum of Science and Industry'
WHEN C.Organization = 'NCH Foundation' THEN 'Northwest Community Hospital Foundation'
WHEN C.Organization LIKE '%Ohio State University%' THEN 'The Ohio State University'
WHEN C.Organization = 'ONU' THEN 'Ohio Northern University'
WHEN C.Organization = 'OSU Foundation' THEN 'Oregon State University Foundation'
WHEN C.Organization = 'RFU' THEN 'Rosalind Franklin University'
WHEN C.Organization = 'RSNA' THEN 'Radiological Society of North America'
WHEN C.Organization LIKE 'Rush %' THEN 'Rush University Medical Center'
WHEN C.Organization LIKE 'Saint Anthony Hospital%' THEN 'Saint Anthony Hospital Foundation'
WHEN C.Organization LIKE 'Saint Mary%%Minnesota%' THEN 'Saint Mary’s University of Minnesota'
WHEN C.Organization = 'san jose state univ' THEN 'San Jose State University'
WHEN C.Organization LIKE 'University of Illinois Chicago%' THEN 'University of Illinois Chicago'
WHEN C.Organization = 'UIC' THEN 'University of Illinois Chicago'
WHEN C.Organization = 'UIF' THEN 'University of Illinois Foundation'
WHEN C.Organization = 'UNC Wilmington' THEN 'University of North Carolina at Wilmington'
WHEN C.Organization = 'UM' THEN 'University of Miami'
WHEN C.Organization LIKE 'U%%Louisville%' THEN 'U of Louisville'
WHEN C.Organization = 'UCI' THEN 'University of California, Irvine'
WHEN C.Organization = 'UC Santa Cruz' THEN 'University of California, Santa Cruz'
WHEN C.Organization = 'UC Davis' THEN 'University of California, Davis'
WHEN C.Organization = 'UC Berkeley' THEN 'University of California, Berkeley'
WHEN C.Organization = 'Texas State' THEN 'Texas State University'
WHEN C.Organization LIKE 'NorthShore%%H%' THEN 'NorthShore University Health System Foundation'
WHEN C.Organization IN ('KU Endowment') THEN 'Kansas University Endowment Association'
WHEN C.Organization IN ('LCMS') THEN 'Lutheran Church – Missouri Synod'
WHEN C.Organization IN ('LCV') THEN 'League of Conservation Voters'
WHEN C.Organization LIKE '%Make%%wish%%il%'THEN 'Make-A-Wish Illinois'
WHEN C.Organization IN ('MFA') THEN 'Museum of Fine Arts, Boston'
ELSE C.Organization END,''),'The University of North Carolina','University of North Carolina') AS "Corrected Org Name",

CASE 
WHEN C.Organization = 'University of Texas at Austin, Dell Medical School' THEN 'Dell Medical School'
WHEN C.Organization = 'University of North Texas' THEN 'Health Science Center'
WHEN C.Organization = 'University of Michigan - College of LSA' THEN 'College of Literature, Science, and the Arts'
WHEN C.Organization = 'Georgetown University Law Center' THEN 'Law Center'
WHEN C.Organization LIKE '%Carbondale%' THEN 'Carbondale'
WHEN C.Organization LIKE '%Edwardsville%' THEN 'Edwardsville'
WHEN C.Organization = 'SIUE' THEN 'Edwardsville'
WHEN C.Organization LIKE '%Feinberg%%Medicine%' THEN 'Feinberg School of Medicine'
WHEN C.Organization LIKE '%Kellogg%' THEN 'Kellogg School of Management'
WHEN C.Organization = 'Northwestern University Libraries' THEN 'Libraries'
WHEN C.Organization = 'Northwestern University - Foundation Relation' THEN 'Foundation Relations'
WHEN C.Organization = 'University of Miami Miller School of Medicine' THEN 'Miller School of Medicine'
WHEN C.Organization = 'UNICEF Canada' THEN 'UNICEF Canada'
WHEN C.Organization = 'UNICEF USA' THEN 'UNICEF USA'
WHEN C.Organization = 'The Salvation Army Chicago Metropolitan Divison' THEN 'Chicago Metropolitan Divison'
WHEN C.Organization LIKE '%Booth%' THEN 'Booth School of Business'
WHEN C.Organization LIKE 'U%%Chicago%%Medicine%%Sciences%' THEN 'Medicine & Biological Sciences'
WHEN C.Organization = 'Columbia Business School' THEN 'Columbia Business School'
WHEN C.Organization IN ('IU Lilly Family School of Philanthropy') THEN 'Lilly Family School of Philanthropy'
WHEN C.Organization IN ('University of Illinois Chicago John Marshall Law School') THEN 'John Marshall Law School'
WHEN C.Organization IN ('University of Illinois Chicago, College of Pharmacy') THEN 'College of Pharmacy'
ELSE '' END AS "Sub-Org"
 
FROM [APRA-IL].[dbo].Contacts C WITH (NOLOCK)

--ORDER BY
--"Org"

GO


