CREATE VIEW [dbo].[Contact_Field_Values_Pivoted] AS 

-- Pivot table with one row and five columns
SELECT 
[Contact ID],
[Archived],
[Donor],
[Event registrant],
[Member],
[Suspended member],
[Event announcements],
[Member emails and newsletters],
[Email delivery disabled],
[Email delivery disabled automatically],
[Receiving emails disabled],
[Balance],
[Total donated],
[Registered for specific event], 
[Profile last updated], 
[Profile last updated by], 
[Creation date], 
[Last login date], 
[Administrator role], 
[Notes], 
[Terms of use accepted], 
[Subscription source], 
[Member ID], 
[First Name], 
[Last Name], 
[Preferred Pronouns], 
[Title], 
[Organization], 
[Organization Type], 
[Address Line 1], 
[Address Line 2], 
[City], 
[State], 
[Zip Code], 
[Country], 
[Phone], 
[E-Mail], 
[Website], 
[Twitter Handle], 
[Interested in volunteering with APRA-IL?], 
[Volunteering Interest], 
[Anything else we should know?], 
[Member role], 
[Member since], 
[Renewal due], 
[Membership level ID], 
[Access to profile by others], 
[Renewal date last changed], 
[Level last changed], 
[Bundle ID], 
[Membership status], 
[Membership enabled], 
[Group participation], 
[Years in Prospect Development], 
[What track do you identify with most in regards to your daily work?], 
[What track are you most interested in for programming?]
FROM (
    SELECT 
    CFV.[Contact ID],
	CF.[Field Name],
	REPLACE(CFV.Value,'[]','') AS "Value"
    FROM DBO.Contact_Field_Values CFV WITH (NOLOCK)
	INNER JOIN DBO.Contact_Fields CF WITH (NOLOCK) ON CFV.[System Code] = CF.[System Code]
) AS SourceTable
PIVOT (
    MIN([Value])
	FOR [Field Name] IN (
	[Archived],
	[Donor],
	[Event registrant],
	[Member],
	[Suspended member],
	[Event announcements],
	[Member emails and newsletters],
	[Email delivery disabled],
	[Email delivery disabled automatically],
	[Receiving emails disabled],
	[Balance],
	[Total donated],
	[Registered for specific event], 
	[Profile last updated], 
	[Profile last updated by], 
	[Creation date], 
	[Last login date], 
	[Administrator role], 
	[Notes], 
	[Terms of use accepted], 
	[Subscription source], 
	[Member ID], 
	[First Name], 
	[Last Name], 
	[Preferred Pronouns], 
	[Title], 
	[Organization], 
	[Organization Type], 
	[Address Line 1], 
	[Address Line 2], 
	[City], 
	[State], 
	[Zip Code], 
	[Country], 
	[Phone], 
	[E-Mail], 
	[Website], 
	[Twitter Handle], 
	[Interested in volunteering with APRA-IL?], 
	[Volunteering Interest], 
	[Anything else we should know?], 
	[Member role], 
	[Member since], 
	[Renewal due], 
	[Membership level ID], 
	[Access to profile by others], 
	[Renewal date last changed], 
	[Level last changed], 
	[Bundle ID], 
	[Membership status], 
	[Membership enabled], 
	[Group participation], 
	[Years in Prospect Development], 
	[What track do you identify with most in regards to your daily work?], 
	[What track are you most interested in for programming?]
	)
) AS PivotTable

GO